---
- name: Confirmation check
  fail: msg="Playbook run confirmation failed"
  when: poweroff_confirmation != "yes"

- name: Enable NETCONF
  connection: network_cli
  junos_netconf:

- name: Shut down all Routing Engine
  connection: netconf
  junos_command:
    commands:
      - request system power-off
  register: result

- name: Print response
  debug:
    var: result
