---
- name: Display all variables and facts known for a host
  debug:
    var: hostvars[inventory_hostname]
  tags:
    - develop

- name: Enable NETCONF
  connection: network_cli
  junos_netconf:

- name: Power off all JUNOS devices
  connection: netconf
  juniper.device.system:
    action: "shutdown"
