---
- name: Confirmation check
  fail: msg="Playbook run confirmation failed"
  when: poweroff_confirmation != "yes"

- name: Enable NETCONF
  connection: network_cli
  junos_netconf:

#- name: Shut down all Routing Engine
#  connection: netconf
#  juniper.device.system:
#    action: "shutdown"
#    all_re: True
#  register: result

- name: Shut down all Routing Engine
  connection: netconf
  junos_shutdown:
    shutdown: "shutdown"

- name: Print response
  debug:
    var: result
